const {app,BrowserWindow,Tray,Menu,Notification,ipcMain,nativeImage,desktopCapturer,session,dialog,shell}=require("electron"),path=require("path"),fs=require("fs"),{execFile,execFileSync}=require("child_process"),Spotify=require("./core/spotify"),Settings=require("./core/settings"),Voicemeeter=require("./core/voicemeeter"),UIServer=require("./server/ui-server"),log=require("./core/logger"),{autoUpdater}=require("electron-updater");
let win,tray,settingsWin,splash,uninstallWin,trayMenu,currentNotification=null,isQuitting=false,overlayVisible=true,updateQueued=false,iconPath=path.join(__dirname,"assets","icon.ico");
app.setName("Spotify VORB");app.setAppUserModelId("Spotify VORB");
try{execFileSync("taskkill",["/F","/IM","Spotify VORB.exe","/T"],{stdio:"ignore",windowsHide:true})}catch{}
app.commandLine.appendSwitch("disable-logging");const gotLock=app.requestSingleInstanceLock();if(!gotLock)app.quit();
autoUpdater.autoDownload=true;autoUpdater.autoInstallOnAppQuit=true;
autoUpdater.on("error",e=>{log.info("AutoUpdater","Error: "+(e?e.message:"unknown"))});
autoUpdater.on("checking-for-update",()=>{log.info("AutoUpdater","Checking for updates...")});
autoUpdater.on("update-available",i=>{log.info("AutoUpdater","Update available: v"+i.version);showNotification("VORB","Update v"+i.version+" found, downloading...")});
autoUpdater.on("update-not-available",()=>{log.info("AutoUpdater","No update available")});
autoUpdater.on("download-progress",p=>{if(Math.floor(p.percent)%25===0)log.info("AutoUpdater",Math.round(p.percent)+"% downloaded")});
autoUpdater.on("update-downloaded",i=>{log.info("AutoUpdater","Update v"+i.version+" ready to install");showNotification("VORB","Update v"+i.version+" ready — restart to install");updateQueued=true});
function createWindow(){win=new BrowserWindow({width:460,height:460,frame:false,transparent:true,resizable:false,show:false,icon:iconPath,alwaysOnTop:Settings.get("behavior.alwaysOnTop"),webPreferences:{preload:path.join(__dirname,"preload.js"),contextIsolation:true,nodeIntegration:false,backgroundThrottling:false}});win.loadFile(path.join(__dirname,"ui","index.html"));win.setIgnoreMouseEvents(true,{forward:true});win.on("close",e=>{if(!isQuitting){e.preventDefault();win.hide()}})}
function createSettingsWindow(){if(settingsWin){settingsWin.focus();return}settingsWin=new BrowserWindow({width:560,height:640,minWidth:480,minHeight:500,frame:true,resizable:true,alwaysOnTop:false,title:"VORB Settings",icon:iconPath,webPreferences:{preload:path.join(__dirname,"preload.js"),contextIsolation:true,nodeIntegration:false}});settingsWin.loadFile(path.join(__dirname,"ui","settings.html"));settingsWin.setMenu(null);settingsWin.on("closed",()=>{settingsWin=null})}
function openUninstallWindow(){if(uninstallWin){uninstallWin.focus();return}uninstallWin=new BrowserWindow({width:500,height:560,frame:true,resizable:false,title:"Uninstall VORB",icon:iconPath,backgroundColor:"#0b0b0b",webPreferences:{preload:path.join(__dirname,"preload.js"),contextIsolation:true,nodeIntegration:false}});uninstallWin.loadFile(path.join(__dirname,"ui","uninstall.html"));uninstallWin.setMenu(null);uninstallWin.on("closed",()=>{uninstallWin=null})}
function createSplash(){splash=new BrowserWindow({width:400,height:440,frame:false,resizable:false,show:false,icon:iconPath,backgroundColor:"#0b0b0b"});splash.loadFile(path.join(__dirname,"ui","splash.html"));const iconImg=nativeImage.createFromPath(iconPath),iconDataUrl=iconImg.resize({width:96,height:96}).toDataURL();splash.webContents.once("did-finish-load",()=>{const pkg=require("./package.json");splash.webContents.executeJavaScript(`document.getElementById('splashLogo').src=${JSON.stringify(iconDataUrl)};document.getElementById('versionLabel').textContent='v${pkg.version} · Spotify'`)});splash.center();splash.once("ready-to-show",()=>splash.show())}
function showNotification(title,body){try{if(currentNotification)currentNotification.close();currentNotification=new Notification({title,body});currentNotification.show()}catch(e){console.log("NOTIFICATION ERROR:",e.message)}}
function buildTrayMenu(){const hasCreds=Settings.get("spotify.clientId")&&Settings.get("spotify.clientSecret"),hasTokens=Settings.get("spotify.accessToken")&&Settings.get("spotify.refreshToken"),isAuth=hasCreds&&hasTokens,template=[{label:overlayVisible?"Hide Overlay":"Show Overlay",click:()=>{overlayVisible=!overlayVisible;if(overlayVisible)win.show();else win.hide();buildTrayMenu();tray.setContextMenu(trayMenu)}},{label:"Settings",click:()=>createSettingsWindow()},{type:"separator"}];isAuth?(template.push({label:"Reload Spotify Auth",click:()=>Spotify.forceReconnect()}),template.push({label:"Disconnect Spotify",click:()=>{Spotify.manualDisconnect();showNotification("VORB","Disconnected from Spotify");buildTrayMenu();tray.setContextMenu(trayMenu)}})):template.push({label:"Connect to Spotify",click:()=>{if(!hasCreds){showNotification("VORB","Enter your Client ID and Secret in Settings first");createSettingsWindow();return}Spotify.forceReconnect()}});template.push({type:"separator"},{label:"Check for Updates",click:()=>{const url=Settings.get("update.url");if(url){autoUpdater.setFeedURL({provider:"generic",url:url});autoUpdater.checkForUpdates()}else showNotification("VORB","No update URL configured in Settings")}},{type:"separator"},{label:"Uninstall VORB...",click:()=>openUninstallWindow()},{type:"separator"},{label:"Quit",click:()=>{isQuitting=true;app.quit()}});trayMenu=Menu.buildFromTemplate(template);if(tray)tray.setContextMenu(trayMenu)}
function createTray(){try{tray=new Tray(iconPath)}catch{console.warn("Failed to load tray icon from "+iconPath+", using empty");tray=new Tray(nativeImage.createEmpty())}tray.setToolTip("Spotify VORB");buildTrayMenu();tray.on("double-click",()=>{if(win.isVisible())win.hide();else win.show()})}
ipcMain.handle("get-settings",()=>Settings.getAll());
ipcMain.handle("preview-settings",(_,p)=>{const c=Settings.getAll();if(p.ui)c.ui=p.ui;if(p.behavior)c.behavior=p.behavior;if(p.audio)c.audio=p.audio;if(win&&!win.isDestroyed()&&win.webContents&&!win.webContents.isDestroyed())win.webContents.send("settings-changed",c);if(p.behavior?.alwaysOnTop!==undefined&&win&&!win.isDestroyed())win.setAlwaysOnTop(p.behavior.alwaysOnTop);return c});
ipcMain.handle("save-settings",(_,n)=>{const o=Settings.getAll(),os=o.audio?.source,od=o.audio?.customDeviceId;Settings.replaceAll(n);if(win&&!win.isDestroyed())win.setAlwaysOnTop(Settings.get("behavior.alwaysOnTop"));if(win&&!win.isDestroyed()&&win.webContents&&!win.webContents.isDestroyed())win.webContents.send("settings-changed",Settings.getAll());const ns=n.audio?.source,nd=n.audio?.customDeviceId;if(ns!==os||(ns==="custom"&&nd!==od))showNotification("VORB","Audio device changed");const nc=n.spotify?.clientId,nsc=n.spotify?.clientSecret,oc=o.spotify?.clientId,osc=o.spotify?.clientSecret;if(nc&&nsc&&(nc!==oc||nsc!==osc)){log.info("Settings","Spotify credentials changed, reconnecting");Spotify.forceReconnect()}});
ipcMain.handle("start-auth",()=>Spotify.forceReconnect());
ipcMain.handle("disconnect-spotify",()=>{Spotify.manualDisconnect();buildTrayMenu()});
ipcMain.handle("uninstall-vorb",async(_,opts)=>{log.info("Uninstall","Uninstall requested, keepSettings="+opts.keepSettings+", clearCache="+opts.clearCache+", feedback="+(opts.feedback||"(none)"));try{if(!app.isPackaged)return{success:false,message:"Cannot uninstall in development mode — use Add/Remove Programs in Windows Settings."};const installDir=path.dirname(app.getPath("exe"));let uninstallPath=null;try{const files=fs.readdirSync(installDir),match=files.find(f=>f.startsWith("Uninstall")&&f.endsWith(".exe"));if(match)uninstallPath=path.join(installDir,match)}catch{}if(!uninstallPath)return{success:false,message:"Uninstaller not found. Use Add/Remove Programs in Windows Settings."};log.info("Uninstall","Found uninstaller: "+uninstallPath);if(opts.keepSettings){const appDataPath=app.getPath("userData"),backupDir=path.join(app.getPath("temp"),"VORB-settings-backup");if(fs.existsSync(appDataPath)){log.info("Uninstall","Backing up settings to "+backupDir);if(!fs.existsSync(backupDir))fs.mkdirSync(backupDir,{recursive:true});["config.json"].forEach(f=>{const src=path.join(appDataPath,f);if(fs.existsSync(src))fs.copyFileSync(src,path.join(backupDir,f))})}}if(opts.clearCache){try{const cacheDir=path.join(app.getPath("userData"),"Cache");if(fs.existsSync(cacheDir))fs.rmSync(cacheDir,{recursive:true,force:true});log.info("Uninstall","Cache cleared")}catch(e){log.warn("Uninstall","Cache clear failed: "+e.message)}}return new Promise(resolve=>{log.info("Uninstall","Launching uninstaller");execFile(uninstallPath,["/S","_?="+installDir],err=>{if(err){log.error("Uninstall","Uninstaller failed: "+err.message);resolve({success:false,message:"Uninstaller failed: "+err.message})}else{log.info("Uninstall","Uninstaller completed");resolve({success:true,message:"VORB has been uninstalled successfully."})}})})}catch(err){log.error("Uninstall","Uninstall error: "+(err.message||err));return{success:false,message:"Uninstall error: "+(err.message||"Unknown error")}}});
ipcMain.handle("get-desktop-sources",async()=>{try{const sources=await desktopCapturer.getSources({types:["screen","window"],thumbnailSize:{width:0,height:0},fetchWindowIcons:false});return sources.filter(s=>s.name).map(s=>({id:s.id,name:s.id.startsWith("screen:")?"[Screen] "+s.name:"[Window] "+s.name}))}catch{return[]}});
ipcMain.on("audio-data",(_,d)=>UIServer.setAudioData(d));
ipcMain.on("open-url",(_,u)=>shell.openExternal(u));
ipcMain.handle("get-voicemeeter-devices",async()=>Voicemeeter.isVoicemeeterInstalled());
process.on("uncaughtException",error=>{log.error("Main","Uncaught exception: "+(error?.message||error));if(!isQuitting){dialog.showErrorBox("VORB Error",error.message+"\n\n"+error.stack);app.exit(1)}else app.exit(0)});
process.on("unhandledRejection",reason=>{log.error("Main","Unhandled rejection: "+(reason?.message||reason));if(!isQuitting){dialog.showErrorBox("VORB Error",reason?.message||String(reason));app.exit(1)}});
const OBS_ONLY=process.argv.includes("--obs-only");
app.whenReady().then(async()=>{log.clear();log.info("Main","App started"+(OBS_ONLY?" (OBS only mode)":""));Settings.load();UIServer.start(3001);if(!OBS_ONLY){const updateUrl=Settings.get("update.url");if(updateUrl){autoUpdater.setFeedURL({provider:"generic",url:updateUrl});if(Settings.get("update.autoCheck")!==false)autoUpdater.checkForUpdatesAndNotify().catch(()=>{})}}if(OBS_ONLY)return;createSplash();createWindow();win.once("ready-to-show",()=>{if(splash&&!splash.isDestroyed())setTimeout(()=>{if(splash&&!splash.isDestroyed())splash.close();if(win&&!win.isDestroyed())win.show()},3000)});createTray();session.defaultSession.setPermissionRequestHandler((wc,perm,cb)=>{if(perm==="media")return cb(true);cb(false)});let wasConnected=false;Spotify.start(data=>{UIServer.setCurrentData(data);buildTrayMenu();if(win&&!win.isDestroyed()&&win.webContents&&!win.webContents.isDestroyed())win.webContents.send("spotify-update",data);if(settingsWin&&!settingsWin.isDestroyed()&&settingsWin.webContents&&!settingsWin.webContents.isDestroyed())settingsWin.webContents.send("spotify-playing",!!data.isPlaying)},(status,message)=>{const msg=(message||"").toLowerCase();if(status==="pending"){showNotification("Spotify VORB","Connecting...")}else if(status==="success"){if(!wasConnected){wasConnected=true;showNotification("Spotify VORB","Connected!")}}else if(status==="error"){if(msg.includes("session expired")||msg.includes("token")){if(wasConnected){wasConnected=false;showNotification("Spotify VORB","⚠ Disconnected - session lost")}}else if(msg.includes("auth server failed")||msg.includes("port 8888")){showNotification("Spotify VORB","⚠ CRITICAL: Auth server failed")}else if(!wasConnected){showNotification("Spotify VORB","Connection failed")}else showNotification("Spotify VORB","⚠ Error: "+(message||"Unknown error"))}})});
app.on("second-instance",()=>{if(win){if(win.isMinimized())win.restore();if(!win.isVisible())win.show();win.focus()}});
app.on("window-all-closed",()=>{if(process.platform!=="darwin"){isQuitting=true;app.quit()}});
app.on("before-quit",()=>{log.info("Main","App quitting");isQuitting=true;Spotify.stop();UIServer.stop();if(currentNotification)currentNotification.close()});
app.on("will-quit",()=>{if(splash&&!splash.isDestroyed()){splash.close();splash=null}if(tray){tray.destroy();tray=null}if(settingsWin){settingsWin.close();settingsWin=null}if(win){win.close();win=null}});
