const express=require("express"),path=require("path"),fs=require("fs");
let server=null,currentData=null,currentAudioData=null,audioSSEClients=[],spotifySSEClients=[];
function sseWriteAll(c,m){for(let i=c.length-1;i>=0;i--)try{c[i].write(m)}catch{c.splice(i,1)}}
function setCurrentData(d){currentData=d;sseWriteAll(spotifySSEClients,`data: ${JSON.stringify(d)}\n\n`)}
function setAudioData(d){currentAudioData=d;sseWriteAll(audioSSEClients,`data: ${JSON.stringify(d)}\n\n`)}
function start(port=3001){return new Promise(resolve=>{const app=express(),uiPath=path.join(__dirname,"..","ui");app.use((req,res,next)=>{res.set("Cache-Control","no-cache,no-store,must-revalidate");res.set("Pragma","no-cache");res.set("Expires","0");next()});app.use(express.static(uiPath,{etag:false,lastModified:true}));app.get("/current",(req,res)=>{res.json(currentData||{connected:false,isPlaying:false})});app.get("/audio",(req,res)=>{res.json({data:currentAudioData||null})});app.get("/audio-stream",(req,res)=>{res.writeHead(200,{"Content-Type":"text/event-stream","Cache-Control":"no-cache","Connection":"keep-alive"});res.write("data: __connected__\n\n");audioSSEClients.push(res);req.on("close",()=>{const idx=audioSSEClients.indexOf(res);if(idx!==-1)audioSSEClients.splice(idx,1)})});app.get("/spotify-stream",(req,res)=>{res.writeHead(200,{"Content-Type":"text/event-stream","Cache-Control":"no-cache","Connection":"keep-alive"});res.write("data: __connected__\n\n");spotifySSEClients.push(res);req.on("close",()=>{const idx=spotifySSEClients.indexOf(res);if(idx!==-1)spotifySSEClients.splice(idx,1)})});app.get("/settings",(req,res)=>{let cp=path.join(__dirname,"..","settings","config.json");try{const{app}=require("electron");cp=path.join(app.getPath("userData"),"config.json")}catch{}try{if(fs.existsSync(cp)){const d=JSON.parse(fs.readFileSync(cp,"utf-8"));if(d.spotify){delete d.spotify.accessToken;delete d.spotify.refreshToken;delete d.spotify.clientId;delete d.spotify.clientSecret}res.json(d)}else res.json({})}catch{res.json({})}});server=app.listen(port,"127.0.0.1",()=>{console.log(`OBS UI SERVER ON http://127.0.0.1:${port}`);resolve(port)})})}
function stop(){if(server){server.close();server=null}}
function isRunning(){return server!==null&&server.listening}
module.exports={start,stop,setCurrentData,setAudioData,isRunning};
